# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f900e2b9fa7c4cd1ab9cf9f19ecb78021a80771ffad56edac4f2e87583b1d85e87f755fefebbe3844397d930f34a6fcfa3ae16f1d360a3c7fe34f5568ad3d77

test:
  secret_key_base: b3a0d4938e72dcb189798c7ef2ba55e84a04838785832250d2b3977e905706884ea5c5a9adfe4dbc8341b2dda85217a9d4d46485dae27a7912a0a252ce54c766

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
